### ISSUE TITLE
error running methylkit getCorrelation

### ISSUE THREAD

**Issue by avilella** [al2na/methylKit#36] opened 2016-04-19 10:29 UTC
I am running the script below and I get an error, not sure if it's related to the chromosomal naming or something else. Any ideas?

```
#!/usr/bin/Rscript
library(methylKit)
library(tools)
args<-commandArgs(TRUE)

# readBismarkCytosineReport function
devtools::source_gist("4839e615e2401d73fe51")

file.list = list("/data/group/test/ILMN_Run001/ILMN_Run001-12345678/WBGS-oxBS-v1-0250ng-PCR10-R01_S1_L003_R1_001.cutB_pe.sorted.mrgd.combo.CpG_report.txt.gz"
,"/data/group/test/ILMN_Run001/ILMN_Run001-12345678/450K-GM12878.nnn.CpG_report.txt.gz"
)
# This reads straight from the output of bismark, works for both strands
myobj = readBismarkCytosineReport(
        file.list,
          sample.id=list(
strsplit(basename("/data/group/test/ILMN_Run001/ILMN_Run001-12345678/WBGS-oxBS-v1-0250ng-PCR10-R01_S1_L003_R1_001.cutB_pe.sorted.mrgd.combo.CpG_report.txt.gz"), '[_]')[[1]][1],
strsplit(basename("/data/group/test/ILMN_Run001/ILMN_Run001-12345678/450K-GM12878.nnn.CpG_report.txt.gz"), '[_]')[[1]][1]
               ),
        assembly="hg38",
        context="CpG",
treatment=c(1,0),
        min.cov=10)

meth = unite(myobj)

pdf(file="/data/group/test/ILMN_Run001/ILMN_Run001-12345678/Methylkit.02.Meth_CorrelationPlot.s02.m10.pdf"); getCorrelation(meth,plot=T); dev.off()

```

Error:

```
Rscript /data/group/test/ILMN_Run001/ILMN_Run001-12345678/run_methcorrelation.s02.m10.R
Loading required package: methods
Sourcing https://gist.githubusercontent.com/al2na/4839e615e2401d73fe51/raw/936308ae69a3f60aee57b5acb8d49070132a4f78/readBismarkFiles.R
SHA-1 hash of file is c3f50bff59693c2f9764bea7b1f645a58b1502e7
Loading required package: R.utils
Loading required package: R.oo
Loading required package: R.methodsS3
R.methodsS3 v1.7.0 (2015-02-19) successfully loaded. See ?R.methodsS3 for help.
R.oo v1.19.0 (2015-02-27) successfully loaded. See ?R.oo for help.

Attaching package: 'R.oo'

The following objects are masked from 'package:methods':

    getClasses, getMethods

The following objects are masked from 'package:base':

    attach, detach, gc, load, save

R.utils v2.2.0 (2015-12-09) successfully loaded. See ?R.utils for help.

Attaching package: 'R.utils'

The following object is masked from 'package:utils':

    timestamp

The following objects are masked from 'package:base':

    cat, commandArgs, getOption, inherits, isOpen, parse, warnings

Loading required package: data.table
Read 57664572 rows and 7 (of 7) columns from 1.331 GB file in 00:01:05
Warning messages:
1: In fread(filepath, ...) :
  Bumped column 1 to type character on data row 54814099, field contains 'MT'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses the first 5 rows, the middle 5 rows and the last 5 rows, so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.
2: In fread(filepath, ...) :
  Bumped column 1 to type character on data row 368078, field contains 'X'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses the first 5 rows, the middle 5 rows and the last 5 rows, so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.
                              WBGS-oxBS-v1-0250ng-PCR10-R01
WBGS-oxBS-v1-0250ng-PCR10-R01                            NA
450K-GM12878.nnn.CpG                                     NA
                              450K-GM12878.nnn.CpG
WBGS-oxBS-v1-0250ng-PCR10-R01                   NA
450K-GM12878.nnn.CpG                            NA
Error in plot.window(...) : need finite 'xlim' values
Calls: getCorrelation ... localPlot -> plot -> plot.default -> localWindow -> plot.window
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf
Execution halted
```

**Comment by al2na** [comment] 2016-04-25 21:26
the warning is probably chromosome naming issue where R thinks the column
is numeric but turns out to be sth else. I think the other issue is about
NA values, NA values might be a problem for some calculation, although
there shouldn't be any NA values in this case. I would look into file
formats and methylRaw objects to see if there is any anomaly

**Comment by al2na** [comment] 2016-06-02 22:32
I'm closing this, if this is still an issue please send a reproducible example

**Closed by al2na** 2016-06-02 22:32 UTC
